### ISSUE TITLE
Question: does Opener work for links in emails?

### ISSUE THREAD

**Issue by alexandreleroux** [timonus/OpenerManifest#16]
Hi, I have the following question. Opener's description states _"Opener is an app that allows you to open links from the web in apps instead!"_. Does Opener also work for links in emails?

I have the following need: for some reason, links I have from Facebook notification emails (in iOS's Mail app) opens in Safari and not the Facebook app. I wonder if Opener would solve my problem and if links would open in the app instead of Safari. Facebook is supported by Opener according to http://opener.link/apps.html

Thanks a lot - hope to be an Opener customer! :-) -- Alex

**Comment by timonus** [comment]
Opener supports some but not all types on Facebook links. Also, the mail app doesn't support the system share menu. In order to use Opener with a link from Mail you'd need to copy the link and launch the Opener app.

**Comment by alexandreleroux** [comment]
Thanks @timonus
