### ISSUE TITLE
Activity View Icon

### ISSUE THREAD

**Issue by ericwbailey** [timonus/OpenerManifest#17]
Hey there,

This didn't quite feel right as a PR, so hope you don't mind me submitting it as an Issue instead. I whipped up an Activity View icon that conforms to the HIG's guidelines for icons a little bit better. 

I'm a big fan of this app and use it nearly every day, so thanks for hearing me out regardless!

Here's a [link to the SVG icon](https://www.dropbox.com/s/os6ufijwewxa2es/opener.svg?dl=0), and here's a quick comp of how it would look. I'm also more than happy to make tweaks and edits to get it into a format that's easier for you to work with, if you want.

![sample-render](https://cloud.githubusercontent.com/assets/634191/21616249/c209dd5c-d1ae-11e6-9fe4-eb703b326f80.png)

**Comment by timonus** [comment]
Interesting. The Opener icon is already scalable, I actually implemented it as a drawable asset in code. Can you point me to the HIG docs you're describing? I might be able to massage the icon to fit better.

**Comment by timonus** [comment]
Also, please note I like the current icon but will consider switching it up :)

**Comment by ericwbailey** [comment]
Thanks for hearing me out :) 

I'm thinking of this, bolded emphasis mine:

> Use a template image for an action extension icon. A template image uses a mask to create an icon. Use **black and white** with appropriate transparency and antialiasing, and don’t include a drop shadow. Template images should be centered in an area measuring about 70px by 70px.
[Source](https://developer.apple.com/ios/human-interface-guidelines/extensions/sharing-and-actions)

In the screenshot below, you can see how Opener's icon differs a little different than the other icon treatments, both stock Apple-provided and 3rd party. Its treatment is not a solid silhouette, and it extends out nearly to the edge of the square button area, where other icons have a little more padding (added some guides to the screenshot to highlight). I'm pretty sure that ratio is based on the old [iOS 7 icon template](https://applypixels.com/template/ios-app-icon/), but it looks like they've scrubbed it from the docs.

I guess I'm all-in now, so let me plead the case for this nitpick. I think you have an incredibly useful app and a very clever icon to accompany it. With the functionality locked down and working really well, this kind of aesthetic tweak helps the app feel more integrated as a natural part of the existing UI.

I realize I'm kinda coming out of left field here with the suggestion as well, though, so just thanks again for the consideration. I'm not suggesting changing the icon per-say, just its treatment in a specific context. 

![img_0442](https://cloud.githubusercontent.com/assets/634191/21654911/970d7d0c-d285-11e6-9626-f1859600423a.PNG)

**Comment by timonus** [comment]
Wow! Thank you for the incredibly thoughtful explanation. I'll check this out and look into updating it.

**Comment by timonus** [comment]
I've tried a few different iterations on this and none of them have come out in a way that I like. The icon always just looks too tiny. I'm keeping this in mind, but not working on it at the moment.

**Comment by ericwbailey** [comment]
Not a problem at all, I appreciate you taking a look!

**Comment by timonus** [comment]
I think you'll be pleased with the update rolling out today 😊

**Comment by ericwbailey** [comment]
It looks great!
