### ISSUE TITLE
Is it possible to add a URL to a web page using Opener syntax to directly open apps?

### ISSUE THREAD

**Issue by whitneyland** [timonus/OpenerManifest#19]
For example, is it possible to add an HTML link to a web page, and then when Safari iOS browses to that page, and the user clicks on the link, Opener is leveraged to start playing a youtube video at a time stamp.

A conventional URL for doing this would be:
https://youtu.be/WOk4Nyq4sNM?t=0m20s

**The question is, can this example be restructured into a URI than launches Opener, which in turn opens the YouTube app using the given parameters?**

Ideally this would be possible without a user prompt confirming it’s ok for Opener to run the app.  I’ve heard iOS Universal URLs don’t require an prompt. Would that make it at least a possibility?

**Comment by timonus** [comment]
I’d recommend checking this out :) http://www.opener.link/api.html

**Comment by timonus** [comment]
Wow, you’ve done your research!

1. No, there’s no way to avoid the prompt. However, it only shows one time for a given pair of (to, from) apps.
2. I cannot leverage universal links in Opener, they’re functional is completely confined to the OS. You may be able to use them to open links in apps, but in my experience it’s not reliable. That’s why I made Opener.
