### ISSUE TITLE
Crash on open

### ISSUE THREAD

**Issue by 144288** [timonus/OpenerManifest#23]
Thanks for making this app - unfortunately though, I can't test it out, as the app immediately crashes on open, on what appears to be a welcome screen/tutorial. I've deleted and reinstalled a few times, but still no luck. I'm on iOS 12.0.1.

Cheers

**Comment by timonus** [comment]
Today's update (1.6.2) fixed this issue. The issue we caused by a change Apple made to it's iTunes service sometime yesterday.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by 144288** [comment]
awesome - thanks!
