### ISSUE TITLE
aliexpress

### ISSUE THREAD

**Issue by hell4opt** [timonus/OpenerManifest#26]
hi! can u share aliexpress url scheme for open products ?

**Comment by timonus** [comment]
Sure, the rule I use for it is here https://github.com/timonus/OpenerManifest/blob/master/openerManifest-v3.json#L3608-L3645, the URL scheme is `aliexpress://`.

**Comment by hell4opt** [comment]
thx, but it does not work, can u share example of swift code pls :)
