### ISSUE TITLE
App formerly called Grape is now Coderx

### ISSUE THREAD

**Issue by jakebathman** [timonus/OpenerManifest#32]
When opening a repository link (e.g. github.com), the last app listed is Grape. Here's its definition in the manifest: https://github.com/timonus/OpenerManifest/blob/master/openerManifest-v3.json#L4655-L4675

Earlier this year, it seems the app was renamed and given a new icon. The `View` action in Opener still works to show the app. Here's a link to it on the app store: https://apps.apple.com/us/app/coderx-for-github/id1371929193

I'd assume the `grape://` scheme has also changed, but I don't own the app and can't test it.

Thanks!

![Image 3](https://user-images.githubusercontent.com/43112/70460035-0f681380-1a7b-11ea-8222-4030fa4f03e9.png)

**Comment by timonus** [comment]
Resolved in https://github.com/timonus/OpenerManifest/issues/32, thanks for the tip!
