### ISSUE TITLE
Issue: Apple News App open links in Safari

### ISSUE THREAD

**Issue by andrewcrook** [timonus/OpenerManifest#37]
Is there anything that can be done to make opening Apple’s News App articles in Safari from the News app sharing easier with opener? 

It fails to work using share -> opener -> Safari and you end up having to select Safari under the 'other viewing options' category, where it does work, adding additional steps to what should be the same functionality.

**Comment by timonus** [comment]
Ah, great idea! I just made Opener unfurl Apple News URLs when they're opened in Safari in [this commit](https://github.com/timonus/OpenerManifest/commit/8ef54a5ce5724c350089bb8c8191aca6d54d8f4a). Give it a try!
