### ISSUE TITLE
[App] GitHub

### ISSUE THREAD

**Issue by nihaals** [timonus/OpenerManifest#38]
GitHub released their [official app](https://apps.apple.com/gb/app/github/id1477376905) recently

**Comment by timonus** [comment]
Hey! This is my top request at the moment. The GitHub app needs to be update to have a URL scheme that you can open things with, I contacted them a while back and sounds like that’s on the way. Once it’s in I’ll add support to Opener!

**Comment by gracjankn** [comment]
It has been added since then. Somebody could close the issue, please?
