### ISSUE TITLE
[Docs] How to find urlschemes

### ISSUE THREAD

**Issue by nihaals** [timonus/OpenerManifest#40]
Could you add to the README some methods of finding the urlschemes for apps? I couldn’t find anything that wasn’t written like 5 years ago using deprecated tools.

**Comment by andrewcrook** [comment]
I always try to guess using the app’s name.
But you can use a tool such as imazing to get the ipa file of an app.

https://amerhukic.com/finding-the-custom-url-scheme-of-an-ios-app
