### ISSUE TITLE
ability to choose different browser without changing default

### ISSUE THREAD

**Issue by chinarut** [timonus/OpenerManifest#42]
This is both a “pre-sales” question and posting an issue on behalf of someone else posted in a review I don’t know if it has been since addressed:

<img width="672" alt="Opener - review criticizing triaging to different browsers" src="https://user-images.githubusercontent.com/6845061/82128095-3551bc80-976d-11ea-9507-9dcdcb19deac.png">

I am curious if this issues is addressed yet as I have a link I’d like to temporarily open in Chrome and don’t want to change Safari as my default browser.

**Comment by timonus** [comment]
Hey there! Yes, you can now switch browsers without changing your default. To do so, you expand the browser list and choose “Open in Chrome once” from the long press context menu on that option. I added quick browser switching in Opener 1.7 around a year ago.

[Here’s a video of what this looks like](https://www.dropbox.com/s/vauackzqptx2xtc/2020-05-16%2012.33.21.mp4?dl=0)
