### ISSUE TITLE
Opening links in a browser truncates query string

### ISSUE THREAD

**Issue by domgregori** [timonus/OpenerManifest#43]
When opening a link in a browser, Opener truncates the query string.

Example:
http://www.example.com/?search=test

Results in: 
http://www.example.com/?
when opened in browser.

**Comment by timonus** [comment]
@domgregori which browser are you trying? Seems to work fine for Safari but maybe something's broken for another one.

**Comment by domgregori** [comment]
The specific issue I'm having seems to be with links in Mail and sending them to Firefox.

**Comment by timonus** [comment]
@domgregori I'm not able to reproduce this issue. Do you have a sample link or video that shows this?

**Comment by domgregori** [comment]
https://imgur.com/a/JY9cKdE

Here's a video. When I copy and paste the link there is a query string but when I use Opener, it's truncated to ```?```

**Comment by timonus** [comment]
Oh! The reason for this is that I strip off all `utm_*` tracking parameters. All the query params on that URL you shared are tracking parameters.
