### ISSUE TITLE
Add Dailymotion app with example scheme

### ISSUE THREAD

**Issue by andrewcrook** [timonus/OpenerManifest#44]
@timonus  I think this should be a simple one. Please could you add it?

Example

https://www.dailymotion.com/video/x7v8llj

dailymotion://video/x7v8llj

Tested from Safari.

**Comment by timonus** [comment]
You got it ;)

https://github.com/timonus/OpenerManifest/commit/6cc454d3b9e0ac40d49e102b4f42982c5b42dfd2
https://twitter.com/OpenerApp/status/1288267778751782912
