### ISSUE TITLE
Opener does not recognize Pinterest links as Pinterest content

### ISSUE THREAD

**Issue by rekabis** [timonus/OpenerManifest#52]
I am sent a link to a Pinterest pin through Facebook Messenger. I am unable to get Opener to open that link - which _clearly shows_ the Pinterest.ca URL - inside the Pinterest app. Only web browsers are displayed as “acceptable” destinations.

I find it shocking that URLs of extremely famous web services are not yet associated with their apps, such that Opener cannot make that association.

**Comment by timonus** [comment]
Just fixed this in https://github.com/timonus/OpenerManifest/commit/72aba17c96bcb3d9ebb1d740a570b56cdf78a32d, thanks for reporting the issue. If you try again it should work!
