### ISSUE TITLE
X.app PiP URL scheme

### ISSUE THREAD

**Issue by devarty** [timonus/OpenerManifest#61]
Hello!

My app is "X.app": https://apps.apple.com/us/app/x-app/id1533525753

It's basically a browser with a Picture-in-Picture and Fullscreen modes + matching extension, supports YouTube, Vimeo, etc.
All web URLs are allowed.

URL scheme:
xapp://?videoURL=Encoded_URL

Twitter handle: @xapp_company

Thanks!

**Comment by timonus** [comment]
Added in https://github.com/timonus/OpenerManifest/commit/e2db817d3fceda0fa66ea406297ec11cf86b1ce8
