### ISSUE TITLE
Links to twitch clips don’t open correctly

### ISSUE THREAD

**Issue by brendang123** [timonus/OpenerManifest#76]
When opening links to clips on twitch in the twitch app, they open to the “clip” channel, not the clip itself. See attached picture for more detail
![90EA3F07-6B7C-4F52-8D29-05FEC546B2C7](https://user-images.githubusercontent.com/31480921/159909293-43975c9e-b924-417c-bf12-5471fd2c4a95.png)

**Comment by timonus** [comment]
Unfortunately you're right, and it doesn't seem like there's a way I can handle links to clip 😢 I just updated Opener to ignore these kinds of links in https://github.com/timonus/OpenerManifest/commit/bff4978358f544528175da83bb67c39a385b41c5.
